// Generated by https://quicktype.io

export interface LandingInfo {
    navbar: Navbar[];
    hero:   Hero;
    about:  any[];
}

export interface Hero {
    greeting:    string;
    name:        string;
    profession:  string[];
    avatar:      string;
    socialMedia: SocialMedia[];
}

export interface Navbar {
    name: string;
    url:  string;
}
export interface SocialMedia {
    name: string;
    url:  string;
    icon: string;
}
