// Generated by https://quicktype.io
// LandingInfo 
// Generated by https://quicktype.io

export interface LandingInfo {
    navbar:     Navbar[];
    languages:  Languages;
    hero:       Hero;
    experience: Experience;
    skills:     Skills;
    projects:   Projects;
    about:      any[];
}

export interface Experience {
    title:    string;
    subtitle: string;
    jobs:     Job[];
}

export interface Job {
    company:     string;
    period:      string;
    position:    string;
    description?:string;
}

export interface Hero {
    greeting:    string;
    name:        string;
    profession:  Array<number | string>;
    avatar:      string;
    socialMedia: SocialMedia[];
}

export interface SocialMedia {
    name: string;
    url:  string;
    icon: string;
}

export interface Languages {
    es: Language;
    en: Language;
}

export interface Language {
    name:  string;
    image: string;
    code:  string;
}

export interface Navbar {
    name: string;
    url:  string;
}

export interface Projects {
    title:    string;
    subtitle: string;
    projects: Project[];
}

export interface Project {
    name:        string;
    description: string;
    image:       string;
    technology:  string[];
    repository:  string;
    live:        string;
}

export interface Skills {
    title:    string;
    subtitle: string;
    soonText: string;
    skills:   Skill[];
}

export interface Skill {
    name:         string;
    icon:         string;
    soon:         boolean;
    listContent?: string[];
}
